### ISSUE TITLE
scrollbar covers menu icons

### ISSUE THREAD

**Issue by sknebel** [jaredreich/pell#1]
![grafik](https://user-images.githubusercontent.com/1082036/28024634-92f1affa-6591-11e7-87b7-d061824c960f.png)

Firefox on Win10

**Comment by joebubna** [comment]
I just encountered the same thing on Chrome 58.0.3029.110 (64-bit), running on a Mac. Adding "overflow: hidden" would fix the issue.

**Comment by RichiCoder1** [comment]
It's because it should be `overflow-x: auto` rather than `overflow-x: scroll`.

**Comment by tutman96** [comment]
Wouldn't that also cover the buttons if it needed the scrollbar? like on mobile?

**Comment by brooksbecton** [comment]
Looks like the class .pell-actionbar has a fixed height  of 30px. I changed the height to 10% in chrome debug and that helped with cover up. 

Also adding @RichiCoder1 'overflow-x: auto' helped the full screen from having a extraneous toolbar.

**Comment by CodeBrauer** [comment]
Related #7 #9

**Comment by jaredreich** [comment]
Thanks everyone for reporting and commenting, fixed in 722308c
