### ISSUE TITLE
Cannot break out of 'pre' tags 

### ISSUE THREAD

**Issue by ShaheedLegion** [jaredreich/pell#113]
If you type some text at the end of the edit stream (bottom of editable content) and select the last line of text and use the `<pre>` button, there's no way to jump out of the pre tag using only the editor.

Any text typed after the `<pre>` tag was opened will remain open indefinitely. I've tried clicking the `<pre>` button again, but it's not a toggle.

So, it looks like a valid bug.

**Comment by jaredreich** [comment]
This is by design of `contentEditable`. Imagine you were trying to write a code block and every time you pressed enter it broke out of the `<pre>` tag.

The way to escape out of a pre tag is to have the `paragraph` action button on your editor and click that on the line you want.
