### ISSUE TITLE
Get the current position of the cursor 

### ISSUE THREAD

**Issue by adrienpoly** [jaredreich/pell#115]
This is more a question than an issue

For an app I would need to split my text editor in two different text editors when I press `ctrl + enter`.

I would, therefore, need to get the current position of the cursor when a `keydown` event is pressed.

With a standard input, I can get this info with `event.target.selectionStart`.

I could find anything similar with Pell editor. Is it possible?

**Comment by jaredreich** [comment]
This is a pretty advanced question, I don't know off the top of my head. Unfortunately you'll have to start off right where I would:
https://www.google.ca/search?q=contenteditable+cursor+position
