### ISSUE TITLE
Question: Custom classes for HTML elements

### ISSUE THREAD

**Issue by marovargovcik** [jaredreich/pell#121]
Is it possible to add custom classes to elements inside pell editor?

I tried looking at document.execCommand() but i hadn't seen feature like this.

`window.pell.init({
    actions: [
        {
            name: "heading1",
            result: () => exec(formatBlock, "<h1 class='myCustomH1Class'>")
        }
    ]
})`

If there is not such a feature, it would be really nice to have this option implemented.

**Comment by marovargovcik** [comment]
After looking in the docs i realised that it's possible to insert HTML markup with anything you really want. Please see my comment in #118.

**Comment by algorys** [comment]
I think #118 and this issue can be split in two dedicated function ?

- One to let user to add class to block

```javascript
{
    name: 'redo',
    icon: '<i class="fa fa-quote-right"></i>',
    class: 'blockquote custom-class'
    result: () => window.pell.exec('formatBlock', '<BLOCKQUOTE>')
}
```
- One to let user insert custom HTML

```javascript
{ 
    name: 'insertHTML', 
    icon: 'M', 
    title: 'Insert HTML', 
    result: () => {
        let value = prompt("Enter valid HTML");
        if (value)
            window.pell.exec("insertHTML", value) 
}
```
