### ISSUE TITLE
When trying to import dies with Unexpected Identifier

### ISSUE THREAD

**Issue by dariodariodario** [jaredreich/pell#130]
When importing using ES6 import like
```
<script type="module" src="http://unpkg.com/pell">
<script>

import pell from "pell"

</script>
```

I get a sintax error saying "Unepected identifier" at the line of the import

**Comment by dariodariodario** [comment]
in chrome

**Comment by jaredreich** [comment]
You can't use "import" syntax in the browser without babel.
