### ISSUE TITLE
How do I add existing content when loading this up?

### ISSUE THREAD

**Issue by gary-woods** [jaredreich/pell#133]
I target this div:

`<div class="pell-target">random text</div>`

and I want `random text` to exist within the editor. How can this be done?

**Comment by jaredreich** [comment]
See the example: https://github.com/jaredreich/pell#example

```js
// editor.content<HTMLElement>
// To change the editor's content:
editor.content.innerHTML = '<b><u><i>Initial content!</i></u></b>'
```
