### ISSUE TITLE
No exported methods in minified dist

### ISSUE THREAD

**Issue by syu93** [jaredreich/pell#137]
Hi,

I'm facing an issue using pell in my application

 ## Step to reproduce (chrome 67 Windows/Debian)
```js
import pell from 'pell';
// or
import {exec, init} from 'pell';
```

## Expected outcome
Loading pell js module

## Actual outcome

`Uncaught SyntaxError: The requested module './node_modules/pell/dist/pell.min.js' does not provide an export named 'exec'`

Or

`Uncaught SyntaxError: The requested module './node_modules/pell/dist/pell.min.js' does not provide an export named 'default'`

I was wondering if I was doing something wrong or if I need some more tooling for it to works.

Thanks

**Comment by jaredreich** [comment]
Are you using ES6+/Babel (ability to use `import`) syntax?

**Comment by syu93** [comment]
No, I'm working on a Polymer 3 implementation of Pell so I'm using plain ES6 browser import

**Comment by jaredreich** [comment]
It definitely does work, must be something related to your setup.

**Comment by MarceloBonifazio** [comment]
This happened to me too .... only solution I found was to change the default

`impor pell from 'pell'` to `import { init } from '../../node_modules/pell/src/pell.js';`

**Comment by AnielloFalcone** [comment]
I can confirm what @jaredreich said, `import pell from 'pell'` works just fine in Typescript and AngularJs.

**Comment by danleyb2** [comment]
> I can confirm what @jaredreich said, `import pell from 'pell'` works just fine in Typescript and AngularJs.

this also worked fine for me using **lit-element**. 
@syu93 i think this is what you need
