### ISSUE TITLE
Pell - actionBar status 

### ISSUE THREAD

**Issue by hellonearthis** [jaredreich/pell#141]
document.queryCommandState()
`state: () => document.queryCommandState('the name of the menu button')`

Not much documents on this function.

Would like to add the same functionality to ☕ 🍪

<img width="585" alt="pell screenshot_11" src="https://user-images.githubusercontent.com/121805/42005094-f3b5445a-7ac6-11e8-9674-0197c25e22fb.png">

**Comment by jaredreich** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandState
