### ISSUE TITLE
How to post these values

### ISSUE THREAD

**Issue by stedem** [jaredreich/pell#142]
The pell works great but in my project i'm still working with ordinary post method. How to capture the pell div content?

**Comment by hellonearthis** [comment]
This is my save file,  I hope it helps.  The main too instructions to look at are:
const list = document.getElementsByClassName("pell-content");
console.log(list[0].textContent)


`function saveFile() {
	console.log("finding the text...");
	const list = document.getElementsByClassName("pell-content");
	console.log(list[0].textContent)
	//  .. the save file routine. 
	SaveAsFile(list[0].textContent,"filename.txt","text/plain;charset=utf-8");
	console.log("over");
	return;`

**Comment by stedem** [comment]
it isn't to export to a certain file, just basic form with (prepopulated field) and a post button. This script looks like to export to filename.txt?

**Comment by stedem** [comment]
it seems

**Comment by jaredreich** [comment]
See `onChange` in README
