### ISSUE TITLE
Focus back to the editor from anywhere

### ISSUE THREAD

**Issue by Arteneko** [jaredreich/pell#144]
I'm having a modal that, on a given callback, gives me an URL.

I tried to embed the URL as `insertImage` using `window.pell.exec('insertImage', completeURL);` in my code, but after the modal appeared, I lost the focus on the editor.

How can I get the focus back ?

Note: I saw someone else having a similar problem (#83), and his closing answer was that he was losing focus. Since he closed it, I assume he managed to get back the right focus on the editor.

**Comment by hellonearthis** [comment]
I used this function.
`function focusEditor() {
	document.getElementsByClassName("pell-content")[0].focus();
}`

**Comment by mkrakowski** [comment]
+1 on preserving cursor position.  I'm adding an auto-complete menu that's triggered by certain chars (e.g @, or #).  It inserts into the correct place but then resets the cursor to the start of the editor.

**Comment by mkrakowski** [comment]
Here's a solution for placing the cursor in a specific area of a contenteditable div.
http://jsfiddle.net/xgz6L/8/

`var node = document.querySelector("div");
node.focus();
var textNode = node.firstChild;
var caret = 10; // insert caret after the 10th character say
var range = document.createRange();
range.setStart(textNode, caret);
range.setEnd(textNode, caret);
var sel = window.getSelection();
sel.removeAllRanges();
sel.addRange(range);`

**Comment by ourfamilygithub** [comment]
@IvanDelsinne [Maybe?](https://gist.github.com/dantaex/543e721be845c18d2f92652c0ebe06aa#file-save-and-restore-contenteditable-selection-js)

**Comment by jaredreich** [comment]
> I used this function.
> `function focusEditor() { document.getElementsByClassName("pell-content")[0].focus(); }`
