### ISSUE TITLE
Indicate text formatting on highlight

### ISSUE THREAD

**Issue by Valkryst** [jaredreich/pell#16]
When a section of text is highlighted, the formatting bar (Bold, Italic, Underlined, etc...) should show which formatting options are applied to the highlighted text.

**Comment by FalkoJoseph** [comment]
Would be really sweet! 👍

**Comment by davidspiess** [comment]
Will this pull request be merged?

**Comment by jaredreich** [comment]
@Valkryst @FalkoJoseph @davidspiess - implemented in 8612415. New release coming soon.
