### ISSUE TITLE
Highlight Formatting Option on Mouseover

### ISSUE THREAD

**Issue by Valkryst** [jaredreich/pell#17]
When the mouse cursor is overtop of a button on the formatting bar (Bold, Italic, Underlined, etc...), the button's background color should change to indicate that it will be used when the user clicks.

It's a little difficult to tell which option is selected until you click, in some cases.

**Comment by deforder** [comment]
Putting `.pell-button:hover {background-color:#ebebe0}` in `pell.css` or  `pell.min.css`  can do the trick.

I don't think there should be any change in original file since this feature seem like an extension (some people might prefer other color or just want it transparent like this).

**Comment by jaredreich** [comment]
As @deforder suggests, customize the CSS to your heart's content 😄
