### ISSUE TITLE
Remove link and image functions

### ISSUE THREAD

**Issue by guymclaren** [jaredreich/pell#175]
**I want to remove the image and link buttons. I can't seem to find a way to do this.** Can anyone advise, please. For my purposes, I need very limited functionality. I literally want people to be able to add bold/italics, headers, and lists. block quotes can also be of benefit, but linking out of my site is a no, as well as images that I can't control the sizing of.

I have figured out how to hide the buttons and stop them from working, but the code still contains the image and link sections just with blank icon and title, If I delete this it breaks the editor.

`link: {
    icon: '',
    title: '',
    },
  image: {
    icon: '',
    title: '',
    }`

**Comment by hawezo** [comment]
I didn't try, but if you provide the `actions` setting when initializing Pell, can't you provide only the actions you want?

**Comment by cpecorari** [comment]
Yes you can just provide array actions at init with only title actions you need 
pell.init({... actions : ["bold", "italic", "heading1", "olist"]})
