### ISSUE TITLE
No way to remove code action once active/clicked

### ISSUE THREAD

**Issue by chriseickemeyerGH** [jaredreich/pell#183]
Once clicking on the `code` button and activating the action, I haven't found anyway to remove the formatting. Clicking on the button again or pressing enter doesn't work to remove `pre` tags.

This is what I'm doing for a work-around:
```
        {
          name: "startCode",
          icon: "&lt;&gt;",
          title: "Start Code Block",
          result: () => exec("formatBlock", "<pre>")
        },

        {
          name: "endCode",
          title: "End Code Block",
          icon: "&lt;/&gt;",
          result: () => exec("formatBlock", "<p>")
        }
```

**Comment by algorys** [comment]
@chriseickemeyerGH see #145 and #178

**Comment by chriseickemeyerGH** [comment]
@algorys thanks, I'll close this issue.
