### ISSUE TITLE
BUG - Custom font-weight for <b> in global stylesheet breaks bold style in pell.

### ISSUE THREAD

**Issue by vedtam** [jaredreich/pell#184]
Hi,

I noticed that the B style wasn't working after a while. Once set on a selection, the toggle didn't responded so I was unable to remove the styling.

Did some digging and saw that `document.queryCommandState(command)` returned `false` with the tag visible in the markdown: `<b>Hello</b>`.

After gutting my app noticed if I disable my global stylesheet it was working as expected, so the issue was at the line:

```
b {
  font-weight: 500;
}
```
after removing it from my global style, things went back to normal, but why styling the `<b>` tag breaks pell?

I put together a working demo, write something and try to toggle B:
[https://codepen.io/vedtam/pen/ZdPMWY](https://codepen.io/vedtam/pen/ZdPMWY)

Regards.

**Comment by algorys** [comment]
@vedtam after some search I found that problem comes with your font weight:

```css
font-weight: 500;
```
(And maybe due to google font api link ?)

Try to put a higher value, like `600` and pell works as expected :wink:

**Comment by vedtam** [comment]
Hi, thanks. Yea I figured that out, it maybe more browser related, but its strange anyway.
