### ISSUE TITLE
Link addition does not work on Firefox

### ISSUE THREAD

**Issue by kasunvp** [jaredreich/pell#186]
The title is self-explanatory. 
Try adding a link here on Firefox https://jaredreich.com/pell/

**Comment by algorys** [comment]
This seems to work on Firefox 68.0.1 (64-bit). Which version of Firefox do you have @kasunvp ?

**Comment by prmsrswt** [comment]
Can confirm this works on Firefox 70.
![image](https://user-images.githubusercontent.com/29674758/66782406-3b3fa080-eef3-11e9-97e0-b246c50c6121.png)

**Comment by bikalay** [comment]
I have the same problem
FF version: 79.0
OS: MacOS (but reproducible on windows too)

Steps to reproduce:

Open https://jaredreich.com/pell/
click link button, enter url to prompt, click ok, nothing appears in editor
if i select some text before, all works fine
