### ISSUE TITLE
Import text

### ISSUE THREAD

**Issue by Wulfheart** [jaredreich/pell#191]
This editor looks really, really promising and I'd love to use it.
However I'd need to edit content after it has been saved. Is it possible to import html output?

**Comment by algorys** [comment]
You can use the `onChange` event, please see https://github.com/jaredreich/pell#api

**Comment by jellysquider** [comment]
isn't it only for exporting html?

``` js // <Function>, required
// Use the output html, triggered by element's `oninput` event
onChange: html => console.log(html)
```

I'd love to have import functionality as well.

**Comment by jaredreich** [comment]
@Wulfheart Can you please elaborate? I'm not sure what you mean by "after it has been saved".

@jellysquider Can you describe what kind of pseudo-code you're looking for with "importing"?

Appreciate the clarifications folsk.

**Comment by Wulfheart** [comment]
@jaredreich I figured out that it is possible to make a default value in the editor so there is a text inserted at the beginning.

**Comment by jaredreich** [comment]
@Wulfheart Ok cool.

FYI, you can modify the raw HTML in the editor at any point with
```js
editor.content.innerHTML = '<b><u><i>Some content!</i></u></b>'
```

**Comment by Wulfheart** [comment]
Your example is excellent and what I was looking for originally. 
I will close this when I'm on the Laptop and not in the app.

**Comment by jaredreich** [comment]
@Wulfheart Ok. That example line is in the README, but perhaps it's kind of hard to find.

**Comment by sg1asgard** [comment]
@jaredreich 
I'm not sure how to solve this with the Vue example?!

Much appreciated.

**Comment by sg1asgard** [comment]
> @jaredreich
> I'm not sure how to solve this with the Vue example?!
> 
> Much appreciated.

I did this for now, right after pell.init inside mounted():
`this.$refs.editorId.content.innerHTML = this.init_editor_id;`

**Comment by Wulfheart** [comment]
@sg1asgard Maybe this should go in a separate issue.
