### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by sauer2** [jaredreich/pell#2]
Are multiple editor instances possible?
Is it just a matter of calling pell.init a couple of times with different root IDs?

**Comment by DylanPiercey** [comment]
@sauer2 by the looks of the [int function](https://github.com/jaredreich/pell/blob/master/src/pell.js#L111) you are correct. Just call init multiple times.

**Comment by sauer2** [comment]
@DylanPiercey Unfortunately that doesn't work, it breaks the toolbar. (There is only one toolbar on the top of the page.) Renaming those classes on the other hand causes an error that breaks the text widget itself.

**Comment by jaredreich** [comment]
Great issue, will definitely implement this.
