### ISSUE TITLE
is find and replace possible?

### ISSUE THREAD

**Issue by AsishRaju** [jaredreich/pell#200]
i am trying to recreate windows notepad with electron using pell, i wanted to know if `find and replace` can be implemented in pell, i guess not because all the default actions use `exec` and `find and replace` is not a part of it, is there any way to add my own buttons which calls the action you already defined?

**Comment by AnielloFalcone** [comment]
You can still create a custom action and there `String.replace(regex)`. Depending if you want to implement replace one or replace all you will need additional logic, but it shouldn't require too much work though...
