### ISSUE TITLE
Insert table command

### ISSUE THREAD

**Issue by csangus** [jaredreich/pell#201]
Can you make a insert/edit table command?

**Comment by jaredreich** [comment]
Can you write one and paste it here?

**Comment by csangus** [comment]
I want to help, but I do not know.
I looked at the source code of Medium Editor's [tables extension](https://github.com/yabwe/medium-editor-tables), but I do not understand the code.

**Comment by jaredreich** [comment]
Ok - this will certainly never become part of the core pell code, but is a good idea for an extension for V2.0
