### ISSUE TITLE
How to bring Pell actionbar at the bottom of editor

### ISSUE THREAD

**Issue by vikasr111** [jaredreich/pell#206]
Hi,

I am thinking of using Pell in my project instead of Quill considering the smaller size. I want to achieve following while integrating Pell in my project

1. I want to display the actionbar at the bottom of the editor instead of the top (refer screenshot)
2. How to show a placeholder text by default in Pell and hide it when the user types the text?
3. Hide/show certain actions in the actionbar
4. Toggle formatting on the action icon click (Works on bold, italic, strike, underline but not on others such as quote action)

I know some of these might already be there and I might be missing it. But your help is appreciated.
![Screenshot 2020-07-20 at 5 44 48 PM](https://user-images.githubusercontent.com/5301813/87937725-d97c1a80-cab2-11ea-83e4-7d0f1c5e2304.png)

**Comment by buncis** [comment]
to make the action button bottom I think you could just override the default css
