### ISSUE TITLE
How do I set default content inside .pell-content ?

### ISSUE THREAD

**Issue by sg1asgard** [jaredreich/pell#209]
Hi every one,

I need to initialize the `.pell-content ` with default content that comes from the Vuex store in my case.

Much appreciated
George

**Comment by sg1asgard** [comment]
Not sure if it is the best way but I did this for now, right after pell.init inside mounted():
`this.$refs.editorId.content.innerHTML = this.init_editor_id;`

I would be totally interested what other solutions some of you may have in regards to Vue.
Is there a Nuxt integration I do not know about maybe? Thank you so much!

George

**Comment by xch1029** [comment]
emm, another way:
```
const editor = init({});
editor.content.innerHTML = this.init_editor_id;
```
they are basically the same.

**Comment by jaredreich** [comment]
As @xch1029 described, or there is a bit in the README.md that explains how to do this.
