### ISSUE TITLE
How to end a paragraph?

### ISSUE THREAD

**Issue by linghuazaii** [jaredreich/pell#28]

**Comment by deforder** [comment]
@linghuazaii , could you try my commit and check whether this problem still persists or not?

**Comment by linghuazaii** [comment]
@deforder is the demo updated with this fix?

**Comment by deforder** [comment]
@linghuazaii , only `pell.js` and `pell.scss` files are updated. there aren't any change in demo file.

make sure to use updated `dist/pell.js` and `dist/pell.css` file since they are include in demo.html
