### ISSUE TITLE
CKEditor has no dependency on jQuery

### ISSUE THREAD

**Issue by fredck** [jaredreich/pell#31]
The comparison table currently indicates that CKEditor depends on jQuery. That's not correct. CKEditor is pure JavaScript, with no dependencies.

[CKEditor has instead a jQuery integration](https://github.com/ckeditor/ckeditor-dev/blob/master/adapters/jquery.js), which can be used by those who prefer to use the jQuery lingo when integrating CKEditor into their pages.

**Comment by jaredreich** [comment]
Good catch, my bad. Thanks.
