### ISSUE TITLE
Not the simplest WYSIWYG ever! [SEE BELOW]

### ISSUE THREAD

**Issue by MajickTek** [jaredreich/pell#37]
There is a much simpler one here (no dependencies) :
GitHub.com/MajickTek/WYSIWYG

**Comment by MajickTek** [comment]
It has nothing but one HTML file.

**Comment by MajickTek** [comment]
Granted, in mine you type code and it shows the output in real-time. Show it's different than yours.

**Comment by MajickTek** [comment]
This here will be preserved as a reminder that you need to check before you boast.

**Comment by MajickTek** [comment]
But you can't see it if it is closed, nevermind.

**Comment by reznord** [comment]
Its not like yours is the best of all. your editor code can be used for plain static websites, but coming to this repo you can use this across any Javascript applications. So, this has much more compatibility. Not that

**Comment by jaredreich** [comment]
![image](https://user-images.githubusercontent.com/8563847/28213139-fe7cfc52-6861-11e7-9358-59845ec0622f.png)

**Comment by reznord** [comment]
On the mark 😂

**Comment by jaredreich** [comment]
Re-opening for hilarity.

**Comment by MajickTek** [comment]
The repository will be moved to a new location. Just saying :)

**Comment by MajickTek** [comment]
This is the new placeGitHub.com/MajickTek/JESSE-RUDERMAN

**Comment by deforder** [comment]
you should do some research before posting. 

- your code demonstrates about how to build a simple text-editor while this project acting like a library itself which can be used directly in our project as a component.
- your code requires users have IT knowledge in coding (those HTML tags).
- your code is hard to customize. (both style and code)
- your code is hard to read. (those a,b,c,d,e,f,g variable remind me of those days during my first coding lesson.) 

lastly, you should learn about manners and respect.

**Comment by Simperfit** [comment]
And in any way @MajickTek,

The advertisement in false, because it's not a WYSIWYG, but rather an HTML editor ;)

**Comment by MajickTek** [comment]
case closed

**Comment by MajickTek** [comment]
For future notice: all repos removed. Sorry for the inconvenience.

**Comment by MajickTek** [comment]
That is, all mentioned repos.

**Comment by jaredreich** [comment]
@MajickTek you're one nonsensical comment/issue away from getting blocked.
