### ISSUE TITLE
Allow HTMLElement as root

### ISSUE THREAD

**Issue by gliechtenstein** [jaredreich/pell#40]
Hi, awesome minimal library! I was playing around with pell and found that the `root` option only takes an id string as its value. I think it would be great if it supports HTMLElements as well. That way it's easily pluggable into any framework/library.

Just to make a point, I am working on a library called [cell](https://github.com/intercellular/cell), and currently the only way to integrate pell into cell is by using the default syntax, I have to have an `id` set to the pell element. Here's an example https://jsfiddle.net/ps91th2L/2/

However if we allow an `HTMLElement` to be passed as `root` (See the commit here: https://github.com/gliechtenstein/pell/blob/master/src/pell.js#L118), we can get rid of the `id`, resulting in something like this: https://jsfiddle.net/ps91th2L/1/ (Note that I'm passing `this` as root, which in this case is the node itself instead of an id string)

But anyway I'm pretty sure you don't want to add all kinds of features to bloat up the library so just wanted to create an issue instead of sending a PR (it's just that one line change I linked to above)

**Comment by jaredreich** [comment]
Great issue, will implement for sure. Thanks.

**Comment by jaredreich** [comment]
#10 related
