### ISSUE TITLE
text should not lose focus when format buttons are pressed

### ISSUE THREAD

**Issue by gvlx** [jaredreich/pell#51]
Hi,

If the focus is on the text and you press one of the format buttons, the text loses focus.

Maybe there could be a way to return focus to text once the format button press finishes?

**Comment by kuopassa** [comment]
Yes, this is quite important feature to help the user create and edit content.

**Comment by andre-dw** [comment]
Any progress on this? I try to create my own wysiwyg editor with `document.execCommand` and don't want to lose fucus on button press.

**Comment by loliconer** [comment]
@andre-dw Run `div.focus()` after `document.execCommand`

**Comment by jaredreich** [comment]
Implemented in e47671e.
