### ISSUE TITLE
Pre-populate Pell textbox with PHP.

### ISSUE THREAD

**Issue by zelon88** [jaredreich/pell#56]
Hello again!

I was reading [this issue](https://github.com/jaredreich/pell/issues/14) and it did not seem to help.

I am trying to pre-populate the Pell textbox with content loaded by PHP. So far I've tried using PHP to generate a Jscript function that will change the innerHtml of the "pell" div with a PHP variable. 

Here's the code...

> if (isset($_POST['pellOpen']) && $pellOpen !== '') {
>   echo ('
>     function pellOpenData() {
>     document.getElementById(\'pell\').innerHTML = \''.str_replace('"', '', json_encode($pellOpenFileData)).'\'; }
>     
>     window.onload = pellOpenData;'); }

and the Jscript function it generates...

> function pellOpenData() {
> document.getElementById('pell').innerHTML = 'fs<b\/>dfsda<\/b\/>\n'; }

What I get for an output is a textbox with no styles and no options bar at the top. It's just pre-formatted text from the textfile I'm feeding it. 

Any advice would be greatly appreciated.
Thanks guys!

**Comment by ZWkang** [comment]
in fact
div#pell.just a container 
it will generate a div class="pell-content" and the actionbar(it is a default className) if you want to init the container innetHTML
you should document.getElementById('pell-content').innerHTML = 'fs<b/>dfsda</b/>\n'; } After your initialization

**Comment by zelon88** [comment]
Thanks! This looks promising. I will try this tonight and share the results. 

I appreciate the help!

**Comment by zelon88** [comment]
I got it working!!! I appreciate the nudge towards the right direction.

However, I realized that the ID of the content is not 'pell-content'. That's actually the classname. So the code that wound up doing the trick looked more like this.....

>    var pellc = document.getElementsByClassName('pell-content'),
>        i = pellc.length;
>    while(i--) {
>        pellc[i].innerHTML = 'test';
>    }

Thanks again! .
:+1: :100:
