### ISSUE TITLE
[Question] Color support ?

### ISSUE THREAD

**Issue by bigopon** [jaredreich/pell#57]
Hi, this looks so amazing 👍 

Is it possible to add support for text / background color ?

**Comment by jaredreich** [comment]
You can change both of those via adding custom CSS or changing the source SCSS file

**Comment by ClementParis016** [comment]
@bigopon  wasn't your question more about having actions to set text color and text background color instead of the customizing the colors of the editor itself?

**Comment by jaredreich** [comment]
@bigopon @ClementParis016 sorry guys, I definitely misread the question.

Here's a better answer, see the commands `backColor` and `foreColor` at https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand.

These can be implemented as custom actions in pell.
