### ISSUE TITLE
Editor doesn't initialize on the IE 11.

### ISSUE THREAD

**Issue by jakubbakiewicz** [jaredreich/pell#61]
After trying to open the editor on IE the console throws an error:
![przechwytywanie](https://user-images.githubusercontent.com/29751459/28711372-b402c144-7387-11e7-8d0b-722ae48fed7d.PNG)

The same happens for IE 9 and 10, console throws the same exact error for both of those browsers.

**Comment by jaredreich** [comment]
Thanks for this issue. I hate IE, lol.

**Comment by Dafrok** [comment]
It's not a bug dude, you just need a polyfill of `Promise`.

**Comment by cswagerty** [comment]
then can it be closed?

**Comment by jaredreich** [comment]
👌
