### ISSUE TITLE
How do I remove an anchor link

### ISSUE THREAD

**Issue by jackbarham** [jaredreich/pell#67]
I'm really keen on this plugin. However, when using your demo version I add a link there doesn't seem to be a way to remove it. I highlight the linked text, then click on the link icon again (usual UI behaviour) but it brings up another modal box.

Am I missing something?

**Comment by jaredreich** [comment]
This is the default behaviour of the browser's `contentEditable` functionality. You'll have to delete the link (e.g. select the text + backspace), and re-add it with the button.

Unfortunately it's little things like this added all over the place that make existing WYSIWYG editors very large in size.
