### ISSUE TITLE
Demo Style

### ISSUE THREAD

**Issue by chux0519** [jaredreich/pell#7]
It seems has some style problem in demo page
![pic](https://lh3.googleusercontent.com/gP9gaB2xYAwj1IE0OeGvzMMzI9gS-4Dr7bQGEZfNks7qM9FbjB6CbDOQiVJrtZgAX77z1vnC_85f-QSL-xvy4wewSYxepaF6dHsXCl8dpzdGAXI5K_LM2iG9FFSau_OcfVCAQuQdI9F8_a5YqFKlKIM8qeCuApC8FyFgWp2Mpedr2R6hMLmumykcsrn-OlitpDh73OsRFC7hDlY0y2lNUTMx5iiL_crVSBk4HxYX_FWO0T51y0JPRVyDVso6sRSaX40qn3C1Bnw1tt0XbWP4k66eINo3ndRDF2LsDnvedHlzpUenKVxxCwKWWB6xgyewPsywp1yvBQhL6-Y1oIx6snsmTj94T48WWiB_PNJNkuZVyrsdTXTYfLgSHIC_vmRzF__S0hAL18jjagJX5qN4Bys2c-DyNzR0GtPLnYVxNPlOs_nv-fAipzniynqL-MseyYblA6VeHBl4IOfmIk7mwnC2eV0sgRDoZR5V9cSYMfCVtLt3wVDnrkcsdbWvZmGPTLcomLH7jkEhciJCAj-6B1Kq_9V4lHtdxZ_v3V90bJ5WA3QpNifF5TXXX5DTPsyctzHVCZLa=w1248-h703)

**Comment by chux0519** [comment]
notice
```css
.pell-actionbar {
  overflow-x: scroll
}
```

**Comment by CodeBrauer** [comment]
related #9

**Comment by jaredreich** [comment]
Thanks for reporting, fixed in 722308c
