### ISSUE TITLE
Remove horizontal line

### ISSUE THREAD

**Issue by TWUsers** [jaredreich/pell#70]
Hi!
Good job for Pell.
But a little things make me crazy:
1. Can't remove the horizontal line.
2. Can't white under the horizontal line.
3. adding undo et redo doesn't works.

Thanks you for help!

**Comment by drnkwati** [comment]
I have provided a quick fix for this issue. check out the issue
https://github.com/jaredreich/pell/issues/77
Also, you can add more features your self
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands

**Comment by jaredreich** [comment]
@TWUsers 

Point 1:
By horizontal line, do you mean bottom border of the actionbar? If so, you can remove it with:
```css
.pell-actionbar {
  border-bottom: none;
}
```
See the README for how to override styles.

Point 2:
I'm not sure what you mean by "Can't white under the horizontal line"

Point 3:
Undo and redo actions do work. See the README on how to implement and custom actions. Also see https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand > Commands > undo & redo
