### ISSUE TITLE
How to enable for input or textarea

### ISSUE THREAD

**Issue by Lablnet** [jaredreich/pell#71]
How to enable for input or textarea

**Comment by jaredreich** [comment]
Textareas are not compatible with the web API `contentEditable`, which is what powers pell.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

**Comment by Lablnet** [comment]
Sir my question is how to get value form php
I am unable to get value simple that we get form input help me please

**Comment by Lablnet** [comment]
Sorry for poor English but make sense
How to get value in PHP file in textarea or input field we need name attribute but its not work in div

**Comment by jaredreich** [comment]
Unfortunately I am struggling to understand what you're trying to ask.

This library is designed for use with JavaScript and HTML, not PHP, so you may have to point your question towards more advanced PHP developers to find your answer.

Best of luck!

**Comment by zelon88** [comment]
Hi there!

I happen to be a PHP developer who's using Pell in a project. I think what he's looking for is a way to populate the textarea using PHP. Here's my version of Pell with my own PHP library on-top...
https://github.com/zelon88/HRCloud2/tree/master/Applications/Pell

There's a lot going on in dist/PellHRC2Lib.php that allows us to save/load files, but I think the specific code you're looking for is a combination of Jscript and PHP that replaces the textarea content with the contents of a PHP variable...

Like this...
```
      var editor = window.pell.init({
        element: document.getElementById('pell'),
        styleWithCSS: false,
        actions: [
          'bold',
          'underline',
          'italic',
          {
            name: 'zitalic',
            icon: 'Z',
            title: 'Zitalic',
            result: () => window.pell.exec('italic')
          },
          {
            name: 'heading1',
            result: () => window.pell.exec('formatBlock', '<H1>')
          },
          {
            name: 'heading2',
            result: () => window.pell.exec('formatBlock', '<H2>')
          },
          {
            name: 'paragraph',
            result: () => window.pell.exec('formatBlock', '<P>')
          },
          {
            name: 'quote',
            result: () => window.pell.exec('formatBlock', '<BLOCKQUOTE>')
          },
          {
            name: 'olist',
            result: () => window.pell.exec('insertOrderedList')
          },
          {
            name: 'ulist',
            result: () => window.pell.exec('insertUnorderedList')
          },
          {
            name: 'line',
            result: () => window.pell.exec('insertHorizontalRule')
          },
          {
            name: 'undo',
            result: () => window.pell.exec('undo')
          },
          {
            name: 'redo',
            result: () => window.pell.exec('redo')
          },
          {
            name: 'image',
            result: () => {
              const url = window.prompt('Enter the image URL')
              if (url) window.pell.exec('insertImage', ensureHTTP(url))
            }
          },
          {
            name: 'link',
            result: () => {
              const url = window.prompt('Enter the link URL')
              if (url) window.pell.exec('createLink', ensureHTTP(url))
            }
          }
        ],
        onChange: function (html) {
          document.getElementById('textoutput').innerHTML = html;
          document.getElementById('htmloutput').textContent = html;
        }
      })
  document.getElementById('htmloutput').textContent = '<?php echo str_replace('\'', '\\\'', str_replace("\n", '', preg_replace('/\s\s+/', ' ', htmlspecialchars_decode(trim($pellOpenFileData))))); ?>';
<?php
if (isset($_POST['pellOpen']) && $pellOpen !== '') {
  echo('
    var pellc = document.getElementsByClassName(\'pell-content\'),
        i = pellc.length;
    while(i--) {
        pellc[i].innerHTML = \''.str_replace('\'', '\\\'', str_replace("\n", '', preg_replace('/\s\s+/', ' ', htmlspecialchars_decode(trim($pellOpenFileData))))).'\';
    }'); }
?>
```

If we take a look at the last 12 lines or so (careful, I changed some variable names around) we can see some funky code. Literally, we need to break JScript and PHP syntax to get this working (there's probably a better way but I haven't found it yet). We basically llet Pell load a blank textbox, and then we fill it with pre-formatted text.

**Comment by jaredreich** [comment]
Thanks @zelon88 for stepping in and helping out.

**Comment by Gargaj** [comment]
> Unfortunately I am struggling to understand what you're trying to ask.
> This library is designed for use with JavaScript and HTML, not PHP, so you may have to point your question towards more advanced PHP developers to find your answer.

What they were trying to ask for is whether Pell can be utilized as simply a drop-in layer on an existing `<textarea>`  that's already utilized as a data source in a `<form>` - i.e. when pressing submit, the contents of the `<textarea>` will be POSTed, thus making the form work without JavaScript as a raw container for HTML. (The question itself has nothing to do with PHP, although PHP does enjoy a good POST request, admittedly.)

From what I can tell, with Pell you'd need to 1. first create a DIV to fill it with the existing contents of the textarea and 2. then have some sort of `onChange` hook to constantly update the contents of a `<textarea>`.

The solution I found for this is among these lines:
```js
<script>
var textarea = document.getElementById('my-existing-editor');
var fake = document.createElement('div');
var startValue = textarea.value;
textarea.parentNode.insertBefore(fake,textarea);
textarea.style.display = "none";
var editor = pell.init({
  element: fake,
  onChange: html => { textarea.value = html; }
});
editor.content.innerHTML = startValue;
</script>
```
