### ISSUE TITLE
Format Default Output

### ISSUE THREAD

**Issue by Graphettion** [jaredreich/pell#75]
Hello Pell Team,

When you type in the pell editor and press enter, the html output adds a div with text in it. Can you change this to be another element (like a p tag) instead or have all text be wrapped by a p tag? Currently, it sets it to `<div></div>`.

Example, http://recordit.co/O5dBRBdKbw

**Comment by jaredreich** [comment]
This occurs by the design of the official browser API for `contentEditable` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable) and `execCommand` (https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)

**Comment by jaredreich** [comment]
I will investigate if this can become an option for pell...

**Comment by Graphettion** [comment]
This too could be probably be a plugin just for the sake of bulking the editor. I love what you're doing, btw.

**Comment by dogoku** [comment]
You can use `defaultParagraphSeparator` command

In the context of pell:
```
exec('defaultParagraphSeparator', 'p');
```

**Comment by jaredreich** [comment]
@dogoku thanks for the research.
@Graphettion this is implemented in 1742bf9, release coming soon.

**Comment by federicosan** [comment]
> You can use `defaultParagraphSeparator` command
> 
> In the context of pell (maybe wrap in a setting like styleWithCSS):
> 
> ```
> exec('defaultParagraphSeparator', 'p');
> ```
> 
> You can also choose `br`

1. Do you know if when chosing br there is some way to get that the second enter you press start a new paragraph? Hitting enter once would do nothing or add a br, but two consecutive brs would create a new paragrah.
