### ISSUE TITLE
[Question] How can pell to keep the selection in editable area?

### ISSUE THREAD

**Issue by Dafrok** [jaredreich/pell#79]
I found something interesting when I was using pell. I clicked the action button, then execCommand API worked with current selection, it seems everything is OK.But, as far as I know, clicking buttons means blur, blur means losing selection.

If I write a rich editor, I prefer to save the selection on blur and restore it on focus, however, I found handlers like this nowhere in the source code of pell.

How can pell do that?

**Comment by dogoku** [comment]
There's a PR open for this: https://github.com/jaredreich/pell/pull/30
Should be easy for you to just edit the line

**Comment by Dafrok** [comment]
Maybe that PR doesn't matter with my question, because that code is not in the published version.
Let's see this demo page: https://jaredreich.com/pell
You can see that if you click the action button and the selection is still there, however no handlers for this behavior in the source code.

**Comment by dogoku** [comment]
Yes, its not in the published version, because no one merged it. 

I just forked the repo and applied the PRs I liked (eg #27, #30, #36, #69)

**Comment by Dafrok** [comment]
It's not the default behavior, you can just try yourself to add 'focus' & 'blur' event listener on the editable element in the demo page, then click an action button, both of them will be triggered and selection will lose after blur.

**Comment by jaredreich** [comment]
This is browser default behaviour, not implemented by pell.

**Comment by Dafrok** [comment]
Oh, that's a mistake. I'm sorry for this naive question.

**Comment by Dafrok** [comment]
I have tried to create an `a` tag for this case, only the `button` tag will trigger this behavior.
