### ISSUE TITLE
Mozilla Firefox (52.2.1) toolbar view problem

### ISSUE THREAD

**Issue by yetkinozturk** [jaredreich/pell#9]
![image](https://user-images.githubusercontent.com/1516018/28052712-3a72338e-6615-11e7-9e9d-f19f856c2c1b.png)

**Comment by samiheikki** [comment]
Same with Chrome 59 (Windows 10)

**Comment by CodeBrauer** [comment]
I think this is intended to work like this on macOS / mobile:
![gif](https://cl.ly/462i2G3j2H3Z/Screen%20Recording%202017-07-11%20at%2010.10%20vorm..gif)

This can be solved by changing `overflow-x` from `scroll` to `auto`:
https://github.com/jaredreich/pell/blob/e775eeb67eb206f6979a41084542f515d3bf6cbd/src/pell.scss#L35

However on viewports < ~480px the issue will appear again (on any OS that has always-visible scrollbars)

**Comment by jaredreich** [comment]
Thanks for reporting, fixed in 722308c
