### ISSUE TITLE
Is there a way to serialize the data in something that's not HTML?

### ISSUE THREAD

**Issue by adtac** [jaredreich/pell#94]
My use-case: https://github.com/adtac/commento - Commento is a discussion platform that could really use something like pell.js. The principle behind Commento is that it's tiny and fast, so there's a lot of overlap between in our philosophies.

Here's my feature request: when the user creates a piece of text, I want to serialize this in a format to store and re-use later. It has to editable in the future. It can't be HTML because I can't allow unsanitised HTML -- it's perfectly fine if pell produces a custom format that it can understand.

Something like (limited) markdown is perfect. Right now, Commento supports markdown, but showdown.js is ~16 kB. Which isn't much, but smaller is better. It'd be awesome if pell would allow rich text editing, produce a markdown I can store in a database, and then take markdown later to initialise the textarea if I want to edit.

Not sure if all that made sense; feel free to ask me anything if something wasn't clear.

Great job with pell! :)

**Comment by jaredreich** [comment]
Hi @adtac, great work on Commento. I've added a markdown usage example to the README (https://github.com/jaredreich/pell#example-markdown). This should satisfy your request as you could convert to markdown as seen in the example, store that markdown in your database, then later fetch the markdown from the database, convert it back to HTML with a parser like https://github.com/markedjs/marked, then populate the editor with the HTML.

Something like this:

```js
import marked from 'marked'
import { init } from 'pell'
import Turndown from 'turndown'

const { turndown } = new Turndown({ headingStyle: 'atx' })

const editor = init({
  element: document.getElementById('pell'),
  actions: ['bold', 'italic', 'heading1', 'heading2', 'olist', 'ulist'],
  onChange: html => {
    const markdownToSave = turndown(html)
    saveMarkdownToDatabase(markdownToSave)
  },
})

handleFetchedMarkdownFromDatabase = (markdownFromDatabase) => {
  editor.content.innerHTML = marked(markdownFromDatabase)
}
```
