### ISSUE TITLE
KeyboardEvent.which deprecated 

### ISSUE THREAD

**Issue by flurmbo** [jaredreich/pell#96]
Hi! Newbie Javascript programmer here looking through your code. Maybe you knew this already but apparently KeyboardEvent.which is deprecated. According to MDN we're supposed to use KeyboardEvent.key now. So `event.which === 13` should now be `event.key === 'Enter'`, for example. Great editor, by the way!

**Comment by jaredreich** [comment]
@flurmbo Good call, thanks for reporting. Fixed in a5c2489 and available in v1.0.3.
