### ISSUE TITLE
editor.content is not longer working as expected

### ISSUE THREAD

**Issue by okbel** [jaredreich/pell#97]
## editor.content is not longer working as expected

Using this code from Pell's `README`
```
editor.content.innerHTML = '<b><u><i>Initial content!</i></u></b>'
```

Triggers this error
```
Cannot set property 'innerHTML' of undefined
```

This used to work before v1. Thanks!

**Comment by jaredreich** [comment]
@okbel great catch, thanks for reporting. Fixed in 1e7a314. Please upgrade to v1.0.3.

**Comment by okbel** [comment]
For some reason this is not working. Will debug.

**Comment by jaredreich** [comment]
@okbel Does this work for you now in v1.0.4?
