### ISSUE TITLE
Actions global is getting overwritten if there's more than one instance of Pell

### ISSUE THREAD

**Issue by okbel** [jaredreich/pell#99]
Due to this line https://github.com/jaredreich/pell/compare/v1.0.0...master#diff-a277aca7808682fd65fb5984fbbfd7f9R170

Actions obj is getting overwritten with an Array and the next instances lose actions.

Steps to reproduce: 
- Run more than one instance of Pell using actions to override icons.

This is `actions` with the first Pell instance, and the second line is the actions object before being used by the next instance of Pell.
<img width="647" alt="screen shot 2018-03-15 at 7 35 28 am" src="https://user-images.githubusercontent.com/1401559/37458320-7d776f84-2823-11e8-9bfa-34544ca13c7c.png">

**Comment by rndevfx** [comment]
https://github.com/jaredreich/pell/pull/98

**Comment by jaredreich** [comment]
@okbel Thanks for reporting. I accidentally messed up variable scope a few commits ago when making changes to fix something else. This is fixed in 10e4012, please upgrade to v1.0.4.

**Comment by okbel** [comment]
Thanks for addressing the bugs so quickly!
